fullname: Dmitrii Kovrizhnukh
favicon: /assets/images/favicon.svg
logo: /assets/images/12.jpg


show_info: true
age: 22 y.o.
location: Russia
language: Russian, English, ein bißchen Deutsch
phone number: 89119675178

show_contacts: true
mailto: mailto:kovrizhnykh.diu@phystech.edu
cv_pdf_link: https://github.com/HCL-271/HCL-271.github.io/blob/main/pdf


remote_theme: annndruha/minimal-resume@v1.0.0
plugins:
- jekyll-remote-theme


