fullname: Dmitrii Kovrizhnukh
favicon: /assets/images/favicon.svg



show_info: true
location: Russia, Moscow
language: Russian, English, ein bißchen Deutsch
phone number: 89119675178

show_contacts: true
mailto: mailto:kovrizhnykh.diu@phystech.edu
cv_pdf_link: https://github.com/HCL-271/HCL-271.github.io/blob/main/pdf
phone number: 89119675178

remote_theme: annndruha/minimal-resume@v1.0.0
plugins:
- jekyll-remote-theme


