fullname: Дмитрий Коврижных
favicon: /assets/images/favicon.svg
logo: /assets/images/ebA-_ztGqQk.jpg


show_info: true
age: 22 y.o.
location: Россия
language: Русский, Английский С1 и Немецкий В1

show_contacts: true
mailto: mailto:kovrizhnykh.diu@phystech.edu
cv_pdf_link: https://github.com/HCL-271/HCL-271.github.io/blob/main/pdf/hcl-271_github_io_.pdf

remote_theme: annndruha/minimal-resume
plugins:
- jekyll-remote-theme


